# Generated by Django 5.0.6 on 2024-07-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=355, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=355, null=True)),
                ('frm', models.CharField(blank=True, max_length=355, null=True)),
                ('to', models.CharField(blank=True, max_length=355, null=True)),
                ('name_address_of_exporter', models.CharField(blank=True, max_length=355, null=True)),
                ('name_address_of_importer', models.CharField(blank=True, max_length=355, null=True)),
                ('distinguishing_marks', models.CharField(blank=True, max_length=355, null=True)),
                ('declared_point_of_entry', models.CharField(blank=True, max_length=355, null=True)),
                ('total_nm_of_packages', models.CharField(blank=True, max_length=355, null=True)),
                ('total_quantity', models.CharField(blank=True, max_length=355, null=True)),
                ('import_permit_no', models.CharField(blank=True, max_length=355, null=True)),
                ('declared_means_of_conveyance', models.CharField(blank=True, max_length=355, null=True)),
                ('end_use_purpose', models.CharField(blank=True, max_length=355, null=True)),
                ('commodity_class', models.CharField(blank=True, max_length=355, null=True)),
                ('no_of_packages', models.CharField(blank=True, max_length=355, null=True)),
                ('quantity', models.CharField(blank=True, max_length=355, null=True)),
                ('pc_no', models.CharField(blank=True, max_length=355, null=True)),
                ('origin', models.CharField(blank=True, max_length=355, null=True)),
                ('common_name', models.CharField(blank=True, max_length=355, null=True)),
                ('sceintific_name', models.CharField(blank=True, max_length=355, null=True)),
                ('additional_declaration', models.CharField(blank=True, max_length=355, null=True)),
                ('name_and_signature_of_authorized_officer', models.CharField(blank=True, max_length=355, null=True)),
                ('date_of_inspection', models.DateField(blank=True, null=True)),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('place_of_issue', models.CharField(blank=True, max_length=355, null=True)),
                ('concentration_rate', models.CharField(blank=True, max_length=355, null=True)),
                ('treatment', models.CharField(blank=True, max_length=355, null=True)),
                ('treatment_date', models.DateField(blank=True, null=True)),
                ('duration_and_temperature', models.CharField(blank=True, max_length=355, null=True)),
                ('chemicals', models.CharField(blank=True, max_length=355, null=True)),
                ('name_and_signature_of_authorized_officer_2', models.CharField(blank=True, max_length=355, null=True)),
                ('date_of_inspection_2', models.DateField(blank=True, null=True)),
                ('date_of_issue_2', models.DateField(blank=True, null=True)),
                ('place_of_issue_2', models.CharField(blank=True, max_length=355, null=True)),
                ('commodity_class_2', models.JSONField(blank=True, null=True)),
                ('no_of_packages_2', models.JSONField(blank=True, null=True)),
                ('quantity_2', models.JSONField(blank=True, null=True)),
                ('pc_no_2', models.JSONField(blank=True, null=True)),
                ('origin_2', models.JSONField(blank=True, null=True)),
                ('common_name_2', models.JSONField(blank=True, null=True)),
                ('sceintific_name_2', models.JSONField(blank=True, null=True)),
                ('name_and_signature_of_authorized_officer_3', models.CharField(blank=True, max_length=355, null=True)),
                ('date_of_inspection_3', models.DateField(blank=True, null=True)),
                ('date_of_issue_3', models.DateField(blank=True, null=True)),
                ('place_of_issue_3', models.CharField(blank=True, max_length=355, null=True)),
            ],
        ),
    ]
