# Generated by Django 5.0.6 on 2024-07-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='commodity_class_2',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='commodity_class',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='common_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='common_name_2',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='no_of_packages',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='no_of_packages_2',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='origin_2',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='pc_no',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='pc_no_2',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='quantity_2',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='sceintific_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='sceintific_name_2',
        ),
    ]
