# Generated by Django 5.0.6 on 2024-07-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_commodity_class_2_certificate_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_of_inspection',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_of_inspection_2',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_of_inspection_3',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_of_issue',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_of_issue_2',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_of_issue_3',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='treatment_date',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
