# Generated by Django 5.0.6 on 2024-07-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_certificate_date_of_inspection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='date_of_inspection_2',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='date_of_inspection_3',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='date_of_issue_2',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='date_of_issue_3',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='name_and_signature_of_authorized_officer_2',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='name_and_signature_of_authorized_officer_3',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='place_of_issue_2',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='place_of_issue_3',
        ),
    ]
