# Generated by Django 5.0.6 on 2024-08-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_certificate_date_of_inspection_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='declared_means_of_conveyance_left',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='font_size_1',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='font_size_2',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
